### ISSUE TITLE
Redirect option breaks the C2, at least for Python client

### ISSUE THREAD

**Issue by langton** [trustedsec/trevorc2#20]
Link to comment on the relevant commit:

https://github.com/trustedsec/trevorc2/commit/a3c8913b581812687a6f8b5b1eb0f7d7942bb53a#r37429348

**Comment by HackingDave** [comment]
Can confirm this is an issue. Working on it now, thanks!

**Comment by HackingDave** [comment]
Just pushed an update out now, fixes this. Thanks!
