### ISSUE TITLE
[!] Something went wrong, printing error: HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by Spl01ter** [trustedsec/trevorc2#28]
revorC2 - Legitimate Website Covert Channel
Written by: David Kennedy (@HackingDave)
https://www.trustedsec.com
[*] Cloning website: https://github.com/
[*] Site cloned successfully.
[*] Starting Trevor C2 Server...
[*] Next, enter the command you want the victim to execute.
[*] Client uses random intervals, this may take a few.
[*] Type help for usage. Example commands, list, interact.

trevorc2>
*** Received connection from 127.0.0.1 and hostname Johns-MacBook-Air.local with communication sid qmMckcopUtHCDdm for TrevorC2.

trevorc2>interact 1

*** interact with Johns-MacBook-Air.local qmMckcopUtHCDdm.
[*] Dropping into trevorc2 shell...
[*] Use exit or back to select other shells
Johns-MacBook-Air.local:trevorc2>ls
[*] Waiting for command to be executed, be patient, results will be displayed here...

**Comment by xme** [comment]
I had the same issue and took some time to investigate this.
Are you running Python 3.8+?
If it's the case, uninstall pycrypto and replace it with pycryptodome...
My $0.02!

**Comment by Spl01ter** [comment]
@xme I was running it on Python 3.9. I've now switched to Python 3.7 due to errors with other packages but the same error still occurs

**Comment by Spl01ter** [comment]
Resolved! Run agent in Python 2 and server in Python 3.7.
