### ISSUE TITLE
Anyone else run into python errors...

### ISSUE THREAD

**Issue by mkannan22** [trustedsec/trevorc2#4]
File "./trevorc2_client.py", line 101, in <module>
    parse = html.split("")[0]
IndexError: list index out of range

**Comment by trustedsec** [comment]
I'm not able to reproduce this one specifically, but give the new version a shot, I've completely rewritten a lot of that for python2/3 compatibility.

**Comment by mkannan22** [comment]
Thanks for response. New version (0.7) does not show this error anymore.
